### ISSUE TITLE
Script need to be modified following OVH API change

### ISSUE THREAD

**Issue by supr4s** [illuin-tech/ovh-db-backup#2]
Hi,

OVHCloud changed the API used yesterday, causing an error in the programm : 

```
INFO:__main__:Creating a new backup for xxx/xxx
Traceback (most recent call last):
  File "./backup-bdd.py", line 82, in <module>
    backup_url = app.trigger_backup()
                 ^^^^^^^^^^^^^^^^^^^^
  File "./backup-bdd.py", line 56, in trigger_backup
    task = self.client.post(
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/ovh/client.py", line 455, in post
    return self.call("POST", _target, kwargs, _need_auth)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/ovh/client.py", line 535, in call
    raise BadParametersError(json_result.get("message"), response=result)
ovh.exceptions.BadParametersError: The input that you provided isn't valid JSON or not well formatted
```

You need to change the bloc in [__main__.py](https://github.com/illuin-tech/ovh-db-backup/blob/master/ovh_db_backup/__main__.py) : 

```
        task = self.client.post(
            f"/hosting/privateDatabase/{self.service_name}/database/{self.database_name}/dump"
        )
```

With : 

```
        task = self.client.post(
        f"/hosting/privateDatabase/{self.service_name}/database/{self.database_name}/dump",
        sendEmail=False,
        )
```

With this, it works great !

**Comment by pdesgarets** [comment]
Thanks, it is now fixed in the latest version on master and `:latest` docker image
